[workspace]
authors = ["Jonathan Chernoch <33642531+chernobylx@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "saber"
platforms = ["win-64"]
version = "0.1.0"

[activation.env]
SSL_CERT_FILE = ".pixi\\envs\\default\\Lib\\site-packages\\certifi\\cacert.pem"
SSL_CERT_DIR =  ".pixi\\envs\\default\\Lib\\site-packages\\certifi"

[tasks]

[dependencies]
polars = ">=1.41.2,<2"
dataframely = ">=2.10.1,<3"
tqdm = ">=4.68.1,<5"
yarl = ">=1.24.2,<2"
joblib = ">=1.5.3,<2"
duckdb = ">=1.5.3,<2"
ruff = ">=0.15.16,<0.16"
scikit-learn = ">=1.9.0,<2"
panel = ">=1.9.3,<2"
hvplot = ">=0.12.2,<0.13"
holoviews = ">=1.22.1,<2"
datashader = ">=0.19.1,<0.20"
marimo = ">=0.23.9,<0.24"
altair = ">=6.1.0,<7"
ty = ">=0.0.44,<0.0.45"
pyarrow = ">=24.0.0,<25"
vegafusion = ">=2.0.3,<3"
npx = ">=0.1.1,<0.2"
vegafusion-python-embed = ">=1.6.9,<2"
vl-convert-python = ">=2.0.0rc1,<3"
pytest = ">=9.0.3,<10"
anthropic = ">=0.109.1,<0.110"
pydantic-ai-slim = ">=1.106.0,<2"
